//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_Website_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_admin
    {
        public int id { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
