//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_Website_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_category
    {
        public tb_category()
        {
            this.tb_product = new HashSet<tb_product>();
        }
    
        public int c_id { get; set; }
        public string category_name { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    
        public virtual ICollection<tb_product> tb_product { get; set; }
    }
}
