//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_Website_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order
    {
        public int o_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> o_date { get; set; }
        public Nullable<int> o_unitPrice { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> bill { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    
        public virtual tb_invoice tb_invoice { get; set; }
        public virtual tb_product tb_product { get; set; }
        public virtual tb_user tb_user { get; set; }
    }
}
