//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_Website_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product
    {
        public tb_product()
        {
            this.tb_order = new HashSet<tb_order>();
        }
    
        public int p_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> product_price { get; set; }
        public string product_detail { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> brand_id { get; set; }
        public string product_image { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    
        public virtual tb_brand tb_brand { get; set; }
        public virtual tb_category tb_category { get; set; }
        public virtual ICollection<tb_order> tb_order { get; set; }
    }
}
