//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_Website_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_shipment
    {
        public int s_id { get; set; }
        public Nullable<int> userID { get; set; }
        public string fullName { get; set; }
        public string phone_number { get; set; }
        public string shipment_address { get; set; }
        public string email { get; set; }
        public string card_number { get; set; }
        public string card_expiration { get; set; }
        public Nullable<int> total_balance { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    
        public virtual tb_user tb_user { get; set; }
    }
}
