//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_Website_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public tb_user()
        {
            this.tb_invoice = new HashSet<tb_invoice>();
            this.tb_order = new HashSet<tb_order>();
            this.tb_shipment = new HashSet<tb_shipment>();
        }
    
        public int id { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    
        public virtual ICollection<tb_invoice> tb_invoice { get; set; }
        public virtual ICollection<tb_order> tb_order { get; set; }
        public virtual ICollection<tb_shipment> tb_shipment { get; set; }
    }
}
